---
AWSTemplateFormatVersion: 2010-09-09
Description: Cloudformation for deploying ecs-service

Parameters:
  LZStackPrefix:
    Description: Prefix to find values from landing zone
    Type: String
  GitHubUser:
    Description: 'GitHub UserName'
    Type: 'String'
  GitRepo:
    Description: 'URL for Git repo'
    Type: 'String'
  GitBranch:
    Description: 'Branch being deployed'
    Type: 'String'
  GitHubToken:
    Description: 'OAuth Token for repo access'
    Type: 'String'
    NoEcho: true
  ListenerPriority:
    Description: 'Priority in ALB'
    Type: Number
  ListenerPath:
    Description: 'Path on which Microservice is deployed'
    Type: 'String'
  ServiceName: # GitHubUser/GitRepo may have capital letters, need to send separately
    Description: 'Name of the service'
    Type: 'String'

Resources:
  PipelineIamRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action: ['sts:AssumeRole']
          Effect: Allow
          Principal:
            Service: [codepipeline.amazonaws.com]
        Version: '2012-10-17'
      Path: /
      Policies:
        - PolicyName: !Sub ${LZStackPrefix}-service-pipeline # Dynamic
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                - 's3:*'
                - 'codebuild:*'
                - 'cloudformation:CreateStack'
                - 'cloudformation:DescribeStacks'
                - 'cloudformation:DeleteStack'
                - 'cloudformation:UpdateStack'
                - 'cloudformation:CreateChangeSet'
                - 'cloudformation:ExecuteChangeSet'
                - 'cloudformation:DeleteChangeSet'
                - 'cloudformation:DescribeChangeSet'
                - 'cloudformation:SetStackPolicy'
                - 'iam:PassRole'
                - 'sns:Publish'
                 # 'codecommit:BatchGetRepositories'
                 #  - 'codecommit:Get*'
                 #  - 'codecommit:GitPull'
                 #  - 'codecommit:List*'
                 #  - 'codecommit:Update*'
                 #  - 'codecommit:Test*'
                 #  - 'codecommit:UploadArchive'
                Effect: Allow
                Resource: '*'

  BuildIamRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          -
            Action: 'sts:AssumeRole'
            Effect: Allow
            Principal:
              Service: 'codebuild.amazonaws.com'
      Path: /
      Policies:
        -
          PolicyName: CodeBuildGetTemplatesPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              -
                Sid: AccessTemplateBucket
                Effect: Allow
                Action:
                  - s3:GetObject
                Resource:
                  - !Sub
                    - 'arn:aws:s3:::${TEMPLATES_BUCKET}/*'
                    -
                      TEMPLATES_BUCKET:
                        Fn::ImportValue: !Sub ${LZStackPrefix}-service-template-bucket
      ManagedPolicyArns:
        - !Ref CodeBuildStandardPolicy

  CodeBuildStandardPolicy:
    Type: "AWS::IAM::ManagedPolicy"
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Resource: !Sub arn:aws:ecr:${AWS::Region}:${AWS::AccountId}:repository/${Repository}
            Effect: Allow
            Action:
              - ecr:GetDownloadUrlForLayer
              - ecr:BatchGetImage
              - ecr:BatchCheckLayerAvailability
              - ecr:PutImage
              - ecr:InitiateLayerUpload
              - ecr:UploadLayerPart
              - ecr:CompleteLayerUpload
          -
            Sid: AccessToCloudWatchLogs
            Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
              - ecr:GetAuthorizationToken
            Resource:
              - '*'
          -
            Sid: AccessArtifactStore
            Effect: Allow
            Action:
              - s3:GetObject
              - s3:PutObject
              - s3:GetObjectVersion
            Resource:
              - !Sub
                - 'arn:aws:s3:::${ARTIFACTS_BUCKET}/*'
                -
                  ARTIFACTS_BUCKET:
                    Fn::ImportValue: !Sub ${LZStackPrefix}-service-artifact-bucket

  Repository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub ${ServiceName}

  BuildProject:
    Type: "AWS::CodeBuild::Project"
    Properties:
      Description: !Sub 'Checkout code from ${GitHubUser}/${GitRepo} and push to ECR at ${Repository}'
      Name: !Sub build-${ServiceName}-container
      ServiceRole: !Ref BuildIamRole
      Artifacts:
        Type: CODEPIPELINE
      Source:
        Type: CODEPIPELINE
        BuildSpec: |
          version: 0.2
          phases:
            pre_build:
              commands:
                - $(aws ecr get-login --no-include-email)
                - TAG="$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)"
            build:
              commands:
                - docker build --tag "${REPOSITORY_URI}:${TAG}" .
            post_build:
              commands:
                - docker push "${REPOSITORY_URI}:${TAG}"
                - printf '{"tag":"%s"}' $TAG > build.json
                - aws s3 cp  s3://${TEMPLATE_BUCKET}/admin/ecs-workshop-service/cf-templates/common/microservice.yml .
          artifacts:
            files:
              - build.json
              - microservice.yml
      Environment:
        ComputeType: "BUILD_GENERAL1_SMALL"
        Image: "aws/codebuild/docker:17.09.0"
        Type: "LINUX_CONTAINER"
        EnvironmentVariables:
          - Name: AWS_DEFAULT_REGION
            Value: !Ref AWS::Region
          - Name: REPOSITORY_URI
            Value: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${Repository}
          - Name: TEMPLATE_BUCKET
            Value:
              Fn::ImportValue: !Sub ${LZStackPrefix}-service-template-bucket
  TestProject:
    Type: "AWS::CodeBuild::Project"
    Properties:
      Description: !Sub '$Checkout container from ${Repository} and check response on port 80'
      Name: !Sub test-${ServiceName}-container
      ServiceRole: !Ref BuildIamRole
      Artifacts:
        Type: CODEPIPELINE
      Source:
        Type: CODEPIPELINE
        BuildSpec: |
          version: 0.2
          phases:
            pre_build:
              commands:
                - $(aws ecr get-login --no-include-email)
                - export TAG=`cat ${BUILD_JSON} | sed -e 's/{"tag":"\(.*\)"}/\1/g'`
                - echo Testing $REPOSITORY_NAME:$TAG
                - docker pull ${REPOSITORY_URI}:${TAG}
            build:
              commands:
                - docker run -d --name test-container  ${REPOSITORY_URI}:${TAG}
                - export CONTAINER_IP=`docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' test-container`
                - export STATUS_CODE=`curl -I http://$CONTAINER_IP:80/ 2>/dev/null | head -n 1|cut -d ' ' -f2`
                - echo "Got ${STATUS_CODE} from ${CONTAINER_IP}"
                - '[ "$STATUS_CODE" -eq "200" ]'
            post_build:
              commands:
                - docker kill test-container
      Environment:
        ComputeType: "BUILD_GENERAL1_SMALL"
        Image: "aws/codebuild/docker:17.09.0"
        Type: "LINUX_CONTAINER"
        EnvironmentVariables:
          - Name: AWS_DEFAULT_REGION
            Value: !Ref AWS::Region
          - Name: REPOSITORY_URI
            Value: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${Repository}
          - Name: REPOSITORY_NAME
            Value: !Sub ${Repository}
          - Name: BUILD_JSON
            Value: build.json
  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: !Sub ${LZStackPrefix}-${ServiceName}-pipeline
      RestartExecutionOnUpdate: true
      ArtifactStore:
        Location:
          Fn::ImportValue: !Sub ${LZStackPrefix}-service-artifact-bucket
        Type: 'S3'
      RoleArn: !GetAtt PipelineIamRole.Arn
      Stages:
        -
          Name: Source
          Actions:
            -
              Name: AppRepoSource
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: 1
              Configuration:
                Owner: !Ref GitHubUser
                Repo: !Ref GitRepo
                Branch: !Ref GitBranch
                OAuthToken: !Ref GitHubToken
              OutputArtifacts:
                - Name: GitHubArtifact
              RunOrder: '1'
        -
          Name: ContainerBuild
          Actions:
            -
              Name: CodeBuild
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: 1
                Provider: CodeBuild
              Configuration:
                ProjectName: !Sub build-${ServiceName}-container
              InputArtifacts: [Name: 'GitHubArtifact']
              OutputArtifacts: [Name: 'BuildOutput']
              RunOrder: 1
        -
          Name: ContainerTest
          Actions:
            -
              Name: CodeTest
              ActionTypeId:
                Category: Test
                Owner: AWS
                Version: 1
                Provider: CodeBuild
              Configuration:
                ProjectName: !Sub test-${ServiceName}-container
              InputArtifacts: [Name: 'BuildOutput']
              RunOrder: 1
        -
          Name: ServiceDeploy
          Actions:
            -
              Name: Deploy
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: 1
                Provider: CloudFormation
              Configuration:
                ChangeSetName: !Sub Deploy-${ServiceName}-Vanilla-On-${LZStackPrefix}
                ActionMode: CREATE_UPDATE
                RoleArn:
                  Fn::ImportValue: !Sub ${LZStackPrefix}-cloudformation-role-arn
                StackName: !Sub w-deploy-${ServiceName}
                Capabilities: CAPABILITY_NAMED_IAM
                TemplatePath:  BuildOutput::microservice.yml
                RoleArn:
                  Fn::ImportValue: !Sub ${LZStackPrefix}-cloudformation-role-arn
                ParameterOverrides: !Sub |
                  {
                    "ContainerRepository": "${ServiceName}",
                    "ContainerName": "${ServiceName}",
                    "ContainerTag": { "Fn::GetParam" : [ "BuildOutput", "build.json", "tag" ] },
                    "DesiredCount": "1",
                    "ListenerPriority": "${ListenerPriority}",
                    "ListenerPath": "${ListenerPath}",
                    "LZStackPrefix": "${LZStackPrefix}"
                  }
              InputArtifacts: [Name: 'BuildOutput']
